[package]
name = "pillars"
version = "0.1.1"
edition = "2021"

[lib]
name = "pillars"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21.2", features = ["extension-module", "multiple-pymethods"] }
ndarray = { version = "0.15.6", features = ["rayon"] }
numpy = "0.21.0"
pathfinding = "4.10.0"
ordered-float = "4.2.0"

[build-dependencies]
pyo3-build-config = { version = "0.21.2", features = ["extension-module"] }
target-lexicon = "0.12.14"
