name: Setup Nox

on:
  push:
  pull_request:
  
  
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: daisylb/setup-nox@v2.1.0
    - run: nox
    
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: daisylb/setup-nox@v2.1.0
    - run: nox
    
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: daisylb/setup-nox@v2.1.0
    - run: nox
    
